jobs:
  - job: build_wheels_manylinux
    pool:
      vmImage: ubuntu-latest
    variables:
      CIBW_BUILD: "cp3?-manylinux* pp3?-manylinux*"
      CIBW_SKIP: "*-win32 *-macosx_x86_64"
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
      CIBW_DEPENDENCY_VERSIONS: latest
    steps:
      - checkout: self
        submodules: recursive
      - task: UsePythonVersion@0
      - script: python -m pip install --upgrade pip setuptools wheel cibuildwheel
        displayName: Install Python pip tools
      - script: python -m cibuildwheel --output-dir wheelhouse .
        displayName: Build wheel
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: 'wheelhouse'
          artifactName: 'Wheels'

